### ISSUE TITLE
Python.exe errors at end of unittests

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#388]
Testing for #385 and I came across this error when the tests were completed...

```
...
...
...
END OF TEST =========================================

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

![image](https://cloud.githubusercontent.com/assets/3093182/12921817/cc3cddc8-cf03-11e5-84b4-da16348a8338.png)

Perhaps it's something on this machine, or that I'm using ArcGIS 10.3.1. But need to log this and move on, until I can review it further.

**Comment by mfunk** [comment]
Closing, works in 10.4
