### ISSUE TITLE
 Create GRG from Point tool failing in Pro 2.2 build 11661 - module 'arcpy' has no attribute 'LoadSettings'

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#667]
### Tasks to be done - May 16th 2018
- [x] Verify Automated test run on 2.1 and 2.2

-----------------------------
I ran the Create GRG from Point tool in Pro 2.2 build 11661, using the version of the tool found at: [server]\Development\Commercial\Solutions\DefenseSolutions\GriddedReferenceGraphic\6
I had set the coordinate system of the Pro Map to North America Lambert Conformal Conic, zoomed in to NE Ohio, the re-ran using a map in Web Mercator to make sure it wasn't a CS issue. It failed in Web Mercator too.

Err message:
Start Time: Friday, March 2, 2018 1:07:06 PM
Running script CreateGRGFromPoint...
App environment: ARCGIS_PRO
Creating Fishnet Grid
Sorting the grid for labeling
Adding field for labeling the grid
Numbering the grids
Rotating the grid
PYTHON ERRORS:Traceback info:  File "C:\Pro_2_2_IterationTesting_GRG\GriddedReferenceGraphic\ArcGIS Desktop\toolboxes\scripts\GRGUtilities.py", line 785, in GRGFromPoint    RotateFeatureClass(tempSort, outputFeatureClass, rotation, pointExtents[0] + " " + pointExtents[1])Error Info:module 'arcpy' has no attribute 'LoadSettings'
ImageArcPy ERRORS:Start Time: Friday, March 2, 2018 1:07:06 PMAdding Grid to in_memory\tempSort...Succeeded at Friday, March 2, 2018 1:07:06 PM (Elapsed Time: 0.01 seconds)
Completed script Create GRG from Point...
ImageFailed to execute (CreateGRGFromPoint).
Failed at Friday, March 2, 2018 1:07:07 PM (Elapsed Time: 0.45 seconds)

This appears to be offending line:
https://github.com/Esri/solutions-geoprocessing-toolbox/blob/929dee047b21c73dd1f200971330472be38b37eb/clearing_operations/scripts/GRGUtilities.py#L269

![image](https://user-images.githubusercontent.com/3801392/36914943-f1edb1ea-1e1c-11e8-8383-0b7cd30e331f.png)

**Comment by BobBooth** [comment]
@adgiles - This is odd.  
@llsjr2 - you didn't see this in your testing of the Clearing Operations Solution - Toolbox out of sync.

**Comment by BobBooth** [comment]
Re-testing this

**Comment by BobBooth** [comment]
Using tool from:
[servername]Development\Commercial\Solutions\DefenseSolutions\GriddedReferenceGraphic\13
I re-ran the Jenkins build and don't see a version dated today.

**Comment by BobBooth** [comment]
If I create a GRG without rotation, the tool runs fine (in Pro 2.2.0_beta.1 + build.12026 and the 4/9/2018 build of GRG (Jenkins build process didn't seem to produce a newer one):
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/1191d9e0-e895-4652-8e96-27c6b891a398)
However, if I create output with a rotation value set, it fails:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/cbc9e937-dd5e-4c7c-8184-b3e791023633)

still seeing "module 'arcpy' has no attribute 'LoadSettings'" message, though the err message is not exactly the same as it was.

**Comment by BobBooth** [comment]
It is failing at the "Rotating the grid" stage.

**Comment by BobBooth** [comment]
The GRGUtilities.py file does include code that calls arcpy.LoadSettings
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/0dc1a56c-f8dc-430a-8d4a-0b4291d3f2f2)

However, that should be OK, according to the Pro Python doc:
http://pro.arcgis.com/en/pro-app/arcpy/functions/loadsettings.htm

![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/448e977d-88fc-47ad-bde6-feaf589a655e)

**Comment by BobBooth** [comment]
This issue is still a problem, on Pro 2.2.
Possibly Python at Pro 2.2 is not supporting arcpy.LoadSettings?
@topowright  - could you reach out the the GP/Pro Python folks and inquire if there have been any (intentional) changes?

**Comment by BobBooth** [comment]
This tool is working correctly in ArcMap 10.5.0.6491
![image](https://user-images.githubusercontent.com/3801392/39273668-788ae88e-48ad-11e8-98ef-b4a792241c7e.png)

**Comment by BobBooth** [comment]
This tool also works fine at Pro 2.1.0
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/49f5ef55-296b-427f-a6ec-24f1d0f47324)

So Pro 2.2 has an issue.
@topowright

**Comment by lfunkhouser** [comment]
Was this working during previous iteration testing of 2.2?

**Comment by topowright-zz** [comment]
This was found during our last testing of 2.2 if I remember correctly. Bob was able to get this to work in 2.1 and ArcMap. We need to show this to the Pro team and get an understanding of what has changed in ArcGIS Pro 2.2

**Comment by topowright-zz** [comment]
This has been logged in the following issue: 

/ArcGISPro/geoprocessing/issues/1640

**Comment by topowright-zz** [comment]
Moving this back to the sprint backlog being that we cannot work on this without input from core.

**Comment by ACueva** [comment]
From internal GitHub:

```
just replace your
if env_file: arcpy.LoadSettings(env_file)
with
if env_file: arcpy.gp.LoadSettings(env_file)
```

This should work in all versions.

**Comment by csmoore** [comment]
Made the changes above in branch -  https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23667-grg-no-rotate-featureclass - but there are some other problems with this method - RotateFeatureClass - not sure that the Rotate angle has worked on this tool in a while (since [December](https://github.com/Esri/solutions-geoprocessing-toolbox/commit/e2ddfa9704d0ec2f41d790abe39ea013fb13c159)?) - so still looking at this

**Comment by csmoore** [comment]
This is now working in ArcMap/Pro in this branch:  https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23667-grg-no-rotate-featureclass

The only remaining issue is I get a very odd problem in Pro when I run from the test driver - one feature is missing (which causes the test to fail since feature count != rows X cols): 

![image](https://user-images.githubusercontent.com/3090809/39900282-b7abfc46-548e-11e8-959c-48be3a194f7c.png)

**Comment by csmoore** [comment]
Addressed in PR: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/294

**Comment by BobBooth** [comment]
Added code to test for ArcGIS Pro, use the updated syntax in that case.
The tool is working on Pro 2.0.0 with this updated code.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/a15c3ff4-45ff-4bb5-a266-f211fba3af58)

**Comment by BobBooth** [comment]
Tool is also working in ArcMap 10.5 with this update.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/1759ba02-6165-4e6d-8ae7-5bb379e99f05)

Submitted PR: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/296

**Comment by BobBooth** [comment]
Adding test case to checklist test
~~https://github.com/ArcGIS/solutions-defense-test-catalog/blob/master/Tests/Gridded-Reference-Graphic_ArcMap-ArcGIS-Pro.md~~

**Comment by BobBooth** [comment]
Created a new checklist test for the GRG toolset in Military Tools.pyt and included specific step to test issue 667 in it.
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/134

**Comment by BobBooth** [comment]
Removing Verify Automated tag because this (rotation, in Pro) is tested in the automated test now.

**Comment by topowright-zz** [comment]
Tested this manually on build ArcGIS Pro 2.2 - 12584 using a grid angle of 36 with no problem. 

Tested this manually on ArcMap 10.6 with no problems at all. 
Ran the unit test on 2.7 ArcMap 10.6 with no fails. 

I need to run this test on 2.2 and 2.1 to make sure it passes now.

**Comment by kgonzago** [comment]
removing development tag since it's a verification issue via jenkins.

**Comment by ACueva** [comment]
Verified Checklist ~, asked @BobBooth for some minor revisions.  Will re-verify once completed.~

**Comment by ACueva** [comment]
Verified in ArcMap (10.3.1 and 10.6.1) and ArcGIS Pro (2.1, and 2.2)
GRG unit tests are not throwing any errors.
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcGIS%20Pro%20Test%20Runner/101/console
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcMap%20Test%20Runner%20Daily/89/console

**Comment by lfunkhouser** [comment]
Impeded until it can be tested from the production build location.

**Comment by BobBooth** [comment]
Tested on:
Pro 2.2 - 12808
Pro 2.1.0
with the 6/7 build of Military tools from [location]\DefenseSolutions\MilitaryToolsForArcGIS\3.0\35
This issue (667) does not occur on either.
Also tested the other two GRG tools on both and they work.
