### ISSUE TITLE
Clearing Operations 10.4.1 Certification Issue - GRG tools failing

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#430]
>PYTHON ERRORS:
Traceback info:
  File "C:\Users\joe7503\Documents\ArcGIS\Templates\ClearingOperations5.0.0\toolboxes\Scripts\CanvasAreaGRG.py", line 424, in main
    arcpy.Fishnet_ClearingOperations(tempOutput, originCoordinate, yAxisCoordinate, str(cellWidth), str(cellHeight), 0, 0, oppCornerCoordinate, "NO_LABELS", templateExtent, "POLYGON")

>Error Info:
'module' object has no attribute 'Fishnet_ClearingOperations'
ArcPy ERRORS:
Executing: Delete C:\Users\joe7503\Documents\ArcGIS\Templates\ClearingOperations5.0.0\data\Scratch.gdb\GridSize FeatureClass
Start Time: Thu Apr 21 14:38:28 2016
Succeeded at Thu Apr 21 14:38:28 2016 (Elapsed Time: 0.09 seconds)

I know that there was originally a Fishnet tool in earlier versions of the template, which I deleted now that we have the core Fishnet tool. This worked in ArcMap 10.4, but now it's throwing an error. What Fishnet_ClearingOperations is it looking for?

**Comment by joebayles** [comment]
@topowright it is the problem that I thought it was originally, it was looking for the deleted Fishnet tool. The issue was compounded because I was working in two different versions inadvertently.

I'll make a fix this weekend, and update the template appropriately, but I've got it working in 10.4 and 10.4.1, so I'm calling this closed.

Shout out to the Master of Geoprocessing, @mfunk . Thanks for keeping it :100:
